# Generated by Django 5.2.3 on 2025-07-25 08:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono o clase CSS', max_length=50)),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Proyecto',
                'verbose_name_plural': 'Categorías de Proyectos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('coordinates', models.CharField(blank=True, help_text='Latitud,Longitud para mostrar en mapa', max_length=100)),
                ('short_description', models.CharField(help_text='Para mostrar en tarjetas y listados', max_length=300, verbose_name='Descripción corta')),
                ('description', models.TextField(verbose_name='Descripción completa')),
                ('units', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de unidades/viviendas')),
                ('participants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de participantes')),
                ('status', models.CharField(choices=[('planning', 'Planificación'), ('development', 'En desarrollo'), ('construction', 'En construcción'), ('active', 'Activo'), ('completed', 'Completado'), ('paused', 'Pausado')], default='planning', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('estimated_completion', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de finalización')),
                ('features', models.TextField(blank=True, help_text='Una por línea. Ej: Eficiencia energética A+, Zonas comunes, etc.', verbose_name='Características')),
                ('investment_range', models.CharField(blank=True, help_text='Ej: 150.000€ - 200.000€', max_length=100, verbose_name='Rango de inversión')),
                ('financing_type', models.CharField(blank=True, max_length=200, verbose_name='Tipo de financiación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Imagen principal')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar en la página principal', verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', verbose_name='URL del video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='proyectos.projectcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(upload_to='projects/documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=True, help_text='¿Visible para todos los usuarios?', verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proyectos.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Documento del Proyecto',
                'verbose_name_plural': 'Documentos del Proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proyectos.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen del Proyecto',
                'verbose_name_plural': 'Imágenes del Proyecto',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/updates/', verbose_name='Imagen')),
                ('is_milestone', models.BooleanField(default=False, help_text='Marcar si es un hito importante del proyecto', verbose_name='Hito importante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='proyectos.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Actualización del Proyecto',
                'verbose_name_plural': 'Actualizaciones del Proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'is_active'], name='proyectos_p_categor_8d306f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_active'], name='proyectos_p_status_7a2e95_idx'),
        ),
    ]
