# Generated by Django 5.2.3 on 2025-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Para mostrar en tarjetas y listados. Si se deja vacío, se generará automáticamente.', max_length=300, verbose_name='Descripción corta'),
        ),
    ]
