# Generated by Django 5.2.3 on 2025-07-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('proyectos', '0002_make_short_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_projects', to='partners.partner', verbose_name='Partner/Colaborador principal'),
        ),
    ]
