# Generated by Django 5.2.3 on 2025-07-11 09:58

import apps.repositorio.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (ej: folder-open)', max_length=50, verbose_name='Icono')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_public', models.BooleanField(default=True, help_text='Si está desmarcado, solo usuarios registrados pueden acceder', verbose_name='Público')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Dejar vacío para permitir a todos los usuarios registrados', related_name='allowed_directories', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios permitidos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='repositorio.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_directories', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='repositorio.directory', verbose_name='Directorio padre')),
            ],
            options={
                'verbose_name': 'Directorio',
                'verbose_name_plural': 'Directorios',
                'ordering': ['name'],
                'unique_together': {('name', 'parent', 'category')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('file', models.FileField(upload_to=apps.repositorio.models.repository_file_path, validators=[apps.repositorio.models.validate_file_size], verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('license', models.CharField(choices=[('CC0', 'CC0 - Dominio Público'), ('CC-BY', 'CC BY - Atribución'), ('CC-BY-SA', 'CC BY-SA - Atribución-CompartirIgual'), ('CC-BY-NC', 'CC BY-NC - Atribución-NoComercial'), ('CC-BY-NC-SA', 'CC BY-NC-SA - Atribución-NoComercial-CompartirIgual'), ('Apache-2.0', 'Apache License 2.0'), ('MIT', 'MIT License'), ('GPL-3.0', 'GPL v3.0'), ('Copyleft', 'Copyleft'), ('Copyright', 'Copyright - Todos los derechos reservados'), ('Other', 'Otra licencia')], default='CC-BY-SA', max_length=20, verbose_name='Licencia')),
                ('size', models.BigIntegerField(editable=False, verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(editable=False, max_length=100, verbose_name='Tipo MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('is_public', models.BooleanField(default=True, help_text='Si está desmarcado, solo usuarios registrados pueden acceder', verbose_name='Público')),
                ('is_hidden', models.BooleanField(default=False, help_text='Los archivos ocultos no se muestran en el listado', verbose_name='Oculto')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Dejar vacío para permitir a todos los usuarios registrados', related_name='allowed_files', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios permitidos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repositorio.category', verbose_name='Categoría')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repositorio.directory', verbose_name='Directorio')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'directory'], name='repositorio_categor_7b1017_idx'), models.Index(fields=['uploaded_at'], name='repositorio_uploade_841fe2_idx')],
            },
        ),
    ]
