# Generated by Django 5.2.3 on 2025-07-25 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono o clase CSS (ej: architecture, construction, legal)', max_length=100)),
                ('color', models.CharField(default='primary', help_text='Color del tema (primary, secondary, accent, etc.)', max_length=20)),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, help_text='Para mostrar en tarjetas y listados', max_length=300, verbose_name='Descripción corta')),
                ('features', models.TextField(blank=True, help_text='Lista de características separadas por líneas', verbose_name='Características')),
                ('requirements', models.TextField(blank=True, help_text='Requisitos o documentación necesaria', verbose_name='Requisitos')),
                ('duration', models.CharField(blank=True, help_text='Ej: 2-3 semanas, 1 mes, Variable', max_length=100, verbose_name='Duración estimada')),
                ('price_type', models.CharField(choices=[('fixed', 'Precio Fijo'), ('hourly', 'Por Hora'), ('project', 'Por Proyecto'), ('consultation', 'Consulta Gratuita'), ('quote', 'Bajo Presupuesto')], default='quote', max_length=20, verbose_name='Tipo de precio')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mínimo')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio máximo')),
                ('price_note', models.CharField(blank=True, help_text='Ej: IVA no incluido, Precio por m²', max_length=200, verbose_name='Nota sobre el precio')),
                ('provider_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del proveedor')),
                ('provider_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('provider_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('provider_website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Imagen principal')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar en la página principal', verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='oferta.servicecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Respondido')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_inquiries_answered', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='oferta.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Consulta de Servicio',
                'verbose_name_plural': 'Consultas de Servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='oferta_serv_categor_be0c27_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured', 'is_active'], name='oferta_serv_is_feat_02e79c_idx'),
        ),
    ]
