# Generated by Django 5.2.3 on 2025-07-10 19:13

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique_for_date='created_at', verbose_name='URL amigable')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('excerpt', models.TextField(help_text='Resumen breve del artículo para mostrar en la lista', max_length=500, verbose_name='Extracto')),
                ('header_image', models.ImageField(help_text='Imagen principal del artículo (recomendado: 1200x600px)', upload_to='news/headers/%Y/%m/', verbose_name='Imagen de cabecera')),
                ('category', models.CharField(choices=[('General', 'General'), ('Cooperativas', 'Cooperativas'), ('Recursos', 'Recursos'), ('Eventos', 'Eventos'), ('Legal', 'Legal'), ('Proyectos', 'Proyectos'), ('Sostenibilidad', 'Sostenibilidad')], default='General', max_length=50, verbose_name='Categoría')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('featured', models.BooleanField(default=False, help_text='Marcar como noticia destacada', verbose_name='Destacado')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'published'], name='noticias_ne_created_ee98e4_idx'), models.Index(fields=['slug', 'created_at'], name='noticias_ne_slug_28af04_idx')],
            },
        ),
    ]
