# Generated by Django 5.2.3 on 2025-07-24 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (ej: home, building)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Recurso',
                'verbose_name_plural': 'Categorías de Recursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('institucion', 'Institución'), ('organizacion', 'Organización'), ('servicio', 'Servicio'), ('programa', 'Programa'), ('cooperativa', 'Cooperativa'), ('empresa', 'Empresa'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('city', models.CharField(choices=[('malaga', 'Málaga'), ('sevilla', 'Sevilla'), ('granada', 'Granada'), ('cordoba', 'Córdoba'), ('almeria', 'Almería'), ('cadiz', 'Cádiz'), ('huelva', 'Huelva'), ('jaen', 'Jaén')], max_length=50, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('schedule', models.TextField(blank=True, help_text='Horario de atención', verbose_name='Horario')),
                ('services', models.TextField(blank=True, help_text='Lista de servicios separados por comas', verbose_name='Servicios')),
                ('requirements', models.TextField(blank=True, help_text='Requisitos para acceder al recurso', verbose_name='Requisitos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos.resourcecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(upload_to='recursos/documents/', verbose_name='Archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recursos.resource')),
            ],
            options={
                'verbose_name': 'Documento de Recurso',
                'verbose_name_plural': 'Documentos de Recursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recursos/images/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recursos.resource')),
            ],
            options={
                'verbose_name': 'Imagen de Recurso',
                'verbose_name_plural': 'Imágenes de Recursos',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['city', 'type'], name='recursos_re_city_fef197_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_active', 'is_featured'], name='recursos_re_is_acti_31674a_idx'),
        ),
    ]
