# Generated by Django 5.2.3 on 2025-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='city',
            field=models.CharField(help_text='Nombre de la ciudad', max_length=100, verbose_name='Ciudad'),
        ),
    ]
