# Generated by Django 5.2.3 on 2025-07-11 08:09

import apps.chat.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última lectura')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.channel', verbose_name='Canal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de canal',
                'verbose_name_plural': 'Membresías de canal',
                'unique_together': {('user', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Contenido del mensaje con formato Markdown', verbose_name='Contenido')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.chat.models.message_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'pdf', 'docx', 'xlsx', 'doc', 'xls']), apps.chat.models.validate_file_size], verbose_name='Archivo adjunto')),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Imagen'), ('document', 'Documento')], max_length=10, verbose_name='Tipo de archivo')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de edición')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.channel', verbose_name='Canal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel', '-created_at'], name='chat_messag_channel_fb213f_idx'), models.Index(fields=['user', 'created_at'], name='chat_messag_user_id_5b10d9_idx')],
            },
        ),
    ]
